### ISSUE TITLE
Helpers.py file missing?

### ISSUE THREAD

**Issue by acarballosa** [devonmpowell/PyPSI#1]
Hello Devon, I'm a graduate student trying to implement your examples. I was wondering if there is not missing a helpers.py file with some auxiliar functions that you call in the other scripts. Thanks in advance and for this amazing work.

**Comment by devonmpowell** [comment]
Hi there,
Thank you for pointing this out! I have added the helpers.py to the repository.
I'm glad you are finding this useful, may I ask what you are using it for?
Cheers,
Devon

**Comment by acarballosa** [comment]
Hi Devon, I would be delighted to comment you my interests. In fact, I tried to reach you at your Stanford's and Max Planck's mail direction, but my e-mail was sent back, so I guess you didn't receive it?
Cheers,
Alejandro
